package:
  name: bioconductor-chippeakanno
  version: 3.8.4
source:
  fn: ChIPpeakAnno_3.8.4.tar.gz
  url: http://bioconductor.org/packages/release/bioc/src/contrib/ChIPpeakAnno_3.8.4.tar.gz
  md5: fe6a274fa3091edd74d0e402238f9c66
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  build:
    - bioconductor-annotationdbi
    - bioconductor-biobase
    - 'bioconductor-biocgenerics >=0.1.0'
    - bioconductor-biocinstaller
    - bioconductor-biomart
    - bioconductor-biostrings
    - bioconductor-bsgenome
    - bioconductor-ensembldb
    - bioconductor-genomeinfodb
    - bioconductor-genomicalignments
    - bioconductor-genomicfeatures
    - 'bioconductor-genomicranges >=1.23.16'
    - bioconductor-go.db
    - bioconductor-graph
    - 'bioconductor-iranges >=2.5.27'
    - bioconductor-limma
    - bioconductor-multtest
    - bioconductor-rbgl
    - bioconductor-regioner
    - bioconductor-rsamtools
    - 'bioconductor-s4vectors >=0.9.25'
    - bioconductor-summarizedexperiment
    - r
    - r-dbi
    - r-idr
    - r-matrixstats
    - r-seqinr
    - r-venndiagram
  run:
    - bioconductor-annotationdbi
    - bioconductor-biobase
    - 'bioconductor-biocgenerics >=0.1.0'
    - bioconductor-biocinstaller
    - bioconductor-biomart
    - bioconductor-biostrings
    - bioconductor-bsgenome
    - bioconductor-ensembldb
    - bioconductor-genomeinfodb
    - bioconductor-genomicalignments
    - bioconductor-genomicfeatures
    - 'bioconductor-genomicranges >=1.23.16'
    - bioconductor-go.db
    - bioconductor-graph
    - 'bioconductor-iranges >=2.5.27'
    - bioconductor-limma
    - bioconductor-multtest
    - bioconductor-rbgl
    - bioconductor-regioner
    - bioconductor-rsamtools
    - 'bioconductor-s4vectors >=0.9.25'
    - bioconductor-summarizedexperiment
    - r
    - r-dbi
    - r-idr
    - r-matrixstats
    - r-seqinr
    - r-venndiagram
test:
  commands:
    - '$R -e "library(''ChIPpeakAnno'')"'
about:
  home: http://bioconductor.org/packages/release/bioc/html/ChIPpeakAnno.html
  license: 'GPL (>= 2)'
  summary: 'The package includes functions to retrieve the sequences around the peak,
    obtain enriched Gene Ontology (GO) terms, find the nearest gene, exon, miRNA or
    custom features such as most conserved elements and other transcription factor
    binding sites supplied by users. Starting 2.0.5, new functions have been added
    for finding the peaks with bi-directional promoters with summary statistics (peaksNearBDP),
    for summarizing the occurrence of motifs in peaks (summarizePatternInPeaks) and
    for adding other IDs to annotated peaks or enrichedGO (addGeneIDs). This package
    leverages the biomaRt, IRanges, Biostrings, BSgenome, GO.db, multtest and stat
    packages.'
