{% set version = "1.0" %}

package:
  name: vgp-tools-format
  version: {{ version }}

build:
  number: 0

source:
  url: https://github.com/VGP/vgp-tools/archive/25a3c486f20a6e07821c675f0a66e268c6e713ba.tar.gz
  sha256: 64dc1efae8764ce404f98e54a1e7c7fdd2c749a2b7c7882fc80df343953a4df4

requirements:
  build: 
    - {{ compiler("c") }}
    - make

test:
  commands:
    - which VGPzip
    - which VGPseq
    - which VGPpair
    - which VGPpacbio
    - which VGPcloud
    - which Dazz2pbr
    - which Dazz2sxs

about:
    home: https://github.com/VGP/vgp-tools/tree/master/VGP
    license: BSD-3
    license_file: LICENSE
    summary: These command line tools are used for importing and operating on data in VGP-formats.