{% set name = "PretextView" %}
{% set version = "0.1.5" %}
{% set sha256 = "0f55ff455bb748ae9cd3336b6be1efb3c860d04dd690d614c7288c3ff7794e7e" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://github.com/wtsi-hpag/{{ name }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ cdt('mesa-libgl-devel') }}
    - {{ cdt('mesa-dri-drivers') }}
    - {{ cdt('libselinux') }}
    - {{ cdt('libxdamage') }}
    - {{ cdt('libxxf86vm') }}
    - {{ cdt('libxfixes') }}
    - xorg-libxext
    - xorg-libx11
    - make
    - cmake
  host:
    - python
    - glfw

test:
  commands:
    - {{ name }}

about:
  home: https://github.com/wtsi-hpag/PretextView
  license: MIT
  license_file: LICENCE
  license_family: MIT
  summary: Paired REad TEXTure Viewer. OpenGL Powered Pretext Contact Map Viewer.

extra:
  identifiers:
    - doi:10.1093/bioinformatics/btv383
  container:
    # needed for libGL.so.1
    extended-base: true
